### PR TITLE
Loopback client should accept protobuf and json content types

### LINKED ISSUE #2450: bug: loopback client should accept protobuf where possible in addition to json
### Describe the bug

The loopback client is explicitly configured only to accept json. Built-in k8s types support protobuf and we should try to use protobuf internally when possible.

### Steps To Reproduce

In kcp-dev/kubernetes pkg/genericcontrolplane/server.go BuildGenericConfig, we don't set genericConfig.LoopbackClientConfig.ContentConfig.AcceptContentTypes to anything, so it defaults to application/json.

### Expected Behaviour

Loopback client uses protobuf when possible and falls back to json otherwise

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by vincepri**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes https://github.com/kcp-dev/kcp/issues/2450

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/genericcontrolplane/server.go [hunk 1]
```diff
@@ -238,6 +238,9 @@ func BuildGenericConfig(
 	// on a fast local network
 	genericConfig.LoopbackClientConfig.DisableCompression = true
 
+	// Accept both protobuf and application/json for loopback client.``
```
Comment (ncdc) [inline pkg/genericcontrolplane/server.go]:
```suggestion
	// Accept both protobuf and application/json for loopback client.
```

File: pkg/genericcontrolplane/server.go [hunk 2]
```diff
@@ -238,6 +238,9 @@ func BuildGenericConfig(
 	// on a fast local network
 	genericConfig.LoopbackClientConfig.DisableCompression = true
 
+	// Accept both protobuf and application/json for loopback client.
+	genericConfig.LoopbackClientConfig.AcceptContentTypes = "application/vnd.kubernetes.protobuf,application/json"
```
Comment (p0lyn0mial) [inline pkg/genericcontrolplane/server.go:242]: does CRDs support protobuf ? I think that the loopback client mostly deals with CRDs resources.

Comment (ncdc) [reply pkg/genericcontrolplane/server.go:242]: This should allow loopback to use proto for built-in types, and fall back to json for CRDs

**Review by ncdc — APPROVED** [review]
